spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: 'jdbc:postgresql://localhost:5454/icfpc'
    username: 'icfpc'
    password: 'icfpc'
    hikari:
      maximum-pool-size: 2
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: update

service:
  read: false
  calc: false
  upload: false

token: ''
